### ISSUE TITLE
LLL

### ISSUE THREAD

**Issue by mayaankvad** [20avva/PokePython#1]
did u make this yourself or copy it lmaooo

**Comment by 20avva** [comment]
made this myself why.... its bad I know

**Comment by 20avva** [comment]
whoops I forgot to make a gitignore lol

**Comment by 20avva** [comment]
I mean, the everything in resources folder were from https://github.com/msikma/pokesprite

**Comment by mayaankvad** [comment]
well its a lot more code than I would have wrote, and make the GUI work as soon as I clone or provide instructions as to how to run it. This makes it look more ligit

**Comment by mayaankvad** [comment]
and u may want to provide a compiled version

**Comment by mayaankvad** [comment]
¯\_(ツ)_/¯

**Comment by mayaankvad** [comment]
¯\\\_(ツ)\_/¯

**Comment by 20avva** [comment]
I gues yea. This is just in something I’m doing for fun. And I _do_ need a compiled version lol.
